### ISSUE TITLE
Práctica de Estimación de Costos

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/estimacion-de-costos-entrevista-EGAL#1]
[Práctica de estimación de costos.pdf](https://github.com/SistemasTecTlaxiaco/estimacion-de-costos-entrevista-EGAL/files/7585712/Practica.de.estimacion.de.costos.pdf)

**Comment by Anna-Aparicio** [comment]
Calificación 20 puntos, se cumplen todos los puntos de la rúbrica

**Comment by josealfredo79** [comment]
Faltaria agregar a la actividad los flujos de trabajo con GitHub Actions

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
